# Generated by Django 2.0 on 2023-12-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
