# Generated by Django 2.0 on 2023-12-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_auto_20231219_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='active',
            field=models.BooleanField(),
        ),
    ]
